"""Study 1 & 2: teacher-forced probe of how a failure record changes the
probability of re-emitting the failed action.

A *probe item* freezes one decision point of an agent trajectory: the context
up to step t (built by executing the reference actions for real), a plausible
wrong action `a_fail` that would fail at step t, the observation the runtime
would return for it, and the correct action `a_gold`. Because the wrong action
is generated by a fixed perturbation operator rather than sampled from a model,
every model in the ladder sees exactly the same items — the scaling curve
therefore cannot be an artefact of easier items for bigger models.

A *condition* is a way of writing that failure into the context (or not writing
it at all). Scoring one fixed candidate string under several conditions gives
the differences the paper is about.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from .harness import (
    NEGATIVE_INSTRUCTION,
    TrajStep,
    abstract_failure,
)

# --------------------------------------------------------------------------
# Items
# --------------------------------------------------------------------------


@dataclass
class ProbeItem:
    item_id: str
    env: str
    task_id: str
    template: str
    step_index: int
    operator: str
    error_type: str
    system_prompt: str
    goal: str
    prefix_actions: List[str]
    prefix_observations: List[str]
    failed_action: str
    gold_action: str
    #: Observations for the same failed action under different renderings.
    obs_fail: str
    obs_fail_terse: str
    obs_fail_verbose: str
    obs_fail_echo: str
    obs_success: str
    obs_neutral: str
    #: Error text for the distractor used by the `fail_other` placebo.
    obs_fail_other: str = ""
    distractors: List[str] = field(default_factory=list)
    tool: Optional[str] = None
    #: Environment-specific extras kept for the analysis (e.g. whether the
    #: interpreter's own traceback happened to quote a line of the submission).
    meta: Dict[str, Any] = field(default_factory=dict)

    def prefix_steps(self) -> List[TrajStep]:
        return [
            TrajStep(action=a, observation=o, ok=True)
            for a, o in zip(self.prefix_actions, self.prefix_observations)
        ]

    def failed_step(self, observation: Optional[str] = None) -> TrajStep:
        return TrajStep(
            action=self.failed_action,
            observation=observation if observation is not None else self.obs_fail,
            ok=False,
            error_type=self.error_type,
            tool=self.tool,
        )


# --------------------------------------------------------------------------
# Conditions
# --------------------------------------------------------------------------

#: (name, description) for every context we score under.
CONDITION_DOC: Dict[str, str] = {
    "pre": "context before the attempt (baseline)",
    "fail": "attempt + error observation (standard ReAct harness)",
    "succ": "attempt + counterfactual success observation",
    "neut": "attempt + valence-free observation",
    "neut_pad": "attempt + valence-free observation, length-matched to `fail`",
    "abstract": "harness-generated failure description, no verbatim call",
    "fail_echo": "as `fail`, but the error quotes the failed call verbatim",
    "fail_terse": "as `fail`, with the shortest error rendering",
    "fail_verbose": "as `fail`, with the longest error rendering",
    "fail_instr": "as `fail`, plus an explicit do-not-repeat instruction",
    "fail_k2": "the same call fails twice",
    "fail_k3": "the same call fails three times",
    "fail_early": "as `fail`, but the failure precedes the successful steps",
    "fail_other": "a DIFFERENT wrong action failed; the scored one was never written",
    "abstract_min": "bare failure marker, no diagnosis and no verbatim call",
}

CORE_CONDITIONS = ["pre", "fail", "succ", "neut", "abstract"]
EXTENDED_CONDITIONS = [
    "neut_pad",
    "fail_echo",
    "fail_terse",
    "fail_verbose",
    "fail_instr",
    "fail_k2",
    "fail_k3",
    "fail_early",
    "fail_other",
    "abstract_min",
]


def config_free_observation_role(_prefix: str) -> str:
    """Observations always come back as a user turn (see HarnessConfig)."""
    return "user"


def build_condition_messages(
    item: ProbeItem,
    condition: str,
    neutral_obs_padded: Optional[str] = None,
    observation_prefix: str = "Observation: ",
) -> List[Dict[str, str]]:
    """Render the chat messages for one probe condition.

    The only thing that differs between conditions is the failure record; the
    system prompt, the goal and the successful prefix steps are byte-identical.
    """
    system = item.system_prompt
    if condition == "fail_instr":
        system = f"{system}\n{NEGATIVE_INSTRUCTION}"

    msgs: List[Dict[str, str]] = [
        {"role": "system", "content": system},
        {"role": "user", "content": item.goal},
    ]

    def push_ok_steps() -> None:
        for a, o in zip(item.prefix_actions, item.prefix_observations):
            msgs.append({"role": "assistant", "content": a})
            msgs.append({"role": "user", "content": f"{observation_prefix}{o}"})

    def push_failure(obs: str, repeats: int = 1) -> None:
        for _ in range(repeats):
            msgs.append({"role": "assistant", "content": item.failed_action})
            msgs.append({"role": "user", "content": f"{observation_prefix}{obs}"})

    if condition == "fail_early":
        push_failure(item.obs_fail)
        push_ok_steps()
        return msgs

    push_ok_steps()

    if condition == "pre":
        pass
    elif condition == "fail":
        push_failure(item.obs_fail)
    elif condition == "succ":
        push_failure(item.obs_success)
    elif condition == "neut":
        push_failure(item.obs_neutral)
    elif condition == "neut_pad":
        if neutral_obs_padded is None:
            raise ValueError("neut_pad requires a length-matched observation")
        push_failure(neutral_obs_padded)
    elif condition == "abstract":
        msgs.append(
            {"role": "user", "content": abstract_failure(item.failed_step(), 1)}
        )
    elif condition == "abstract_min":
        # Removes the surface form *and* the diagnosis. Isolates how much of the
        # abstraction's benefit comes from the wording we chose for the gloss
        # versus from the mere absence of the failed call.
        msgs.append({"role": "user", "content": "[attempt 1 failed]"})
    elif condition == "fail_other":
        # Placebo: a different plausible-but-wrong call is recorded as having
        # failed. The action we score was never written into the context, so any
        # rise in its probability cannot be surface-form copying of *it*. This
        # separates "a failure happened" from "this string is in the context".
        if not item.distractors:
            raise ValueError("fail_other requires a distractor action")
        other = item.distractors[0]
        msgs.append({"role": "assistant", "content": other})
        msgs.append(
            {
                "role": config_free_observation_role(observation_prefix),
                "content": f"{observation_prefix}{item.obs_fail_other or item.obs_fail}",
            }
        )
    elif condition == "fail_echo":
        push_failure(item.obs_fail_echo)
    elif condition == "fail_terse":
        push_failure(item.obs_fail_terse)
    elif condition == "fail_verbose":
        push_failure(item.obs_fail_verbose)
    elif condition == "fail_instr":
        push_failure(item.obs_fail)
    elif condition == "fail_k2":
        push_failure(item.obs_fail, repeats=2)
    elif condition == "fail_k3":
        push_failure(item.obs_fail, repeats=3)
    else:
        raise KeyError(f"unknown condition {condition!r}")
    return msgs


# --------------------------------------------------------------------------
# Item construction — ToolShed
# --------------------------------------------------------------------------


def build_toolshed_items(
    n_tasks: int = 90,
    seed: int = 20260808,
    max_per_operator: int = 80,
    n_distractors: int = 2,
) -> List[ProbeItem]:
    """Build a balanced probe set from ToolShed.

    Balancing is over *perturbation operator* (which determines the error
    family). Without it the set would be dominated by `tool_typo` and
    `arg_typo`, which apply to every call.
    """
    from .envs.toolshed import ToolShedEnv, parse_action
    from .envs.toolshed_tasks import generate_tasks, perturbations

    # The *primary* rendering does not quote the failed call back to the model,
    # so that the `fail` / `succ` / `neut` contexts contain the action string
    # exactly once each (as the assistant turn). Quoting is studied separately
    # as the `fail_echo` condition, where it is the only thing that changes.
    env_std = ToolShedEnv(verbosity="standard", echo_action=False)
    env_terse = ToolShedEnv(verbosity="terse", echo_action=False)
    env_verbose = ToolShedEnv(verbosity="verbose", echo_action=False)
    env_echo = ToolShedEnv(verbosity="standard", echo_action=True)

    tasks = generate_tasks(n_tasks, seed=seed)
    by_operator: Dict[str, List[ProbeItem]] = {}

    for task in tasks:
        for env in (env_std, env_terse, env_verbose, env_echo):
            env.reset(task)
        system_prompt = env_std.system_prompt(task)
        prefix_actions: List[str] = []
        prefix_observations: List[str] = []

        for step_index, gold in enumerate(task.gold_actions):
            if gold.strip() == "finish()":
                break
            world = env_std.world(task)
            perts = perturbations(gold, world)
            # Distractors: other perturbations of the same gold action. Scoring
            # them lets us report a properly normalised P(repeat) rather than
            # an unnormalised log-probability difference.
            for pert_index, pert in enumerate(perts):
                others = [p.action for p in perts if p.action != pert.action]
                distractors = others[:n_distractors]

                out_other = (
                    env_std.step(task, distractors[0]) if distractors else None
                )
                out_std = env_std.step(task, pert.action)
                out_terse = env_terse.step(task, pert.action)
                out_verbose = env_verbose.step(task, pert.action)
                out_echo = env_echo.step(task, pert.action)
                # A perturbation that unexpectedly succeeds is not usable.
                if out_std.ok:
                    continue
                # Failed calls must not mutate the world; assert by re-checking.
                assert out_std.error_type is not None

                try:
                    tool = parse_action(pert.action).name
                except Exception:  # noqa: BLE001
                    tool = None

                item = ProbeItem(
                    # `pert_index` disambiguates two perturbations that share an
                    # operator name for the same call (e.g. two different malformed
                    # dates). Without it their scores would collide in the analysis.
                    item_id=f"{task.task_id}-s{step_index}-{pert.operator}-{pert_index}",
                    env="toolshed",
                    task_id=task.task_id,
                    template=task.payload["template"],
                    step_index=step_index,
                    operator=pert.operator,
                    error_type=out_std.error_type or "unknown",
                    system_prompt=system_prompt,
                    goal=task.goal,
                    prefix_actions=list(prefix_actions),
                    prefix_observations=list(prefix_observations),
                    failed_action=pert.action,
                    gold_action=gold,
                    obs_fail=out_std.observation,
                    obs_fail_terse=out_terse.observation,
                    obs_fail_verbose=out_verbose.observation,
                    obs_fail_echo=out_echo.observation,
                    obs_success=env_std.success_observation(pert.action, out_std),
                    obs_neutral=env_std.neutral_observation(pert.action, out_std),
                    obs_fail_other=(
                        out_other.observation
                        if out_other is not None and not out_other.ok
                        else ""
                    ),
                    distractors=distractors,
                    tool=tool,
                )
                by_operator.setdefault(pert.operator, []).append(item)

            # Advance the real trajectory with the reference action.
            obs = env_std.step(task, gold)
            assert obs.ok, f"reference action failed: {gold} -> {obs.observation}"
            for env in (env_terse, env_verbose, env_echo):
                env.step(task, gold)
            prefix_actions.append(gold)
            prefix_observations.append(obs.observation)

    items: List[ProbeItem] = []
    for operator in sorted(by_operator):
        items.extend(by_operator[operator][:max_per_operator])
    items.sort(key=lambda it: it.item_id)
    return items


# --------------------------------------------------------------------------
# I/O
# --------------------------------------------------------------------------


def build_coderepair_items(
    n_problems: int = 120,
    seed: int = 20260808,
    max_per_operator: int = 70,
    n_distractors: int = 2,
    data_dir: str = "data/mbpp",
    timeout: float = 10.0,
) -> List[ProbeItem]:
    """Build probe items from MBPP by mutating reference solutions.

    A mutation is kept only if (a) the reference solution passes and (b) the
    mutant actually fails — so every item is a genuine failure with a genuine
    interpreter message, and the "wrong" program is one single edit away from a
    correct one.
    """
    from .envs.coderepair import (
        SYSTEM_PROMPT,
        load_mbpp,
        mutate,
        neutral_observation,
        render_observation,
        run_program,
        success_observation,
    )

    problems = load_mbpp(data_dir)[:n_problems]
    by_operator: Dict[str, List[ProbeItem]] = {}

    for p in problems:
        tests = p["test_list"]
        ref = run_program(p["code"], tests, timeout=timeout)
        if not ref.ok:
            continue  # a handful of MBPP references do not pass their own tests
        muts = mutate(p["code"])
        results = []
        for m in muts:
            r = run_program(m.code, tests, timeout=timeout)
            if not r.ok:
                results.append((m, r))
        if not results:
            continue
        goal = f"{p['prompt']}\n\nThe tests are:\n" + "\n".join(tests)
        for m, r in results:
            others = [(o, rr) for o, rr in results if o.code != m.code]
            distractors = [o.code for o, _ in others][:n_distractors]
            obs_other = (
                render_observation(others[0][1], len(tests), "standard", False,
                                   others[0][0].code)
                if others
                else ""
            )
            obs_fail = render_observation(r, len(tests), "standard", False, m.code)
            quotes = any(
                len(ln.strip()) > 8 and ln.strip() in obs_fail
                for ln in m.code.splitlines()
            )
            item = ProbeItem(
                item_id=f"mbpp-{p['task_id']:04d}-{m.operator}-{results.index((m, r))}",
                env="coderepair",
                task_id=f"mbpp-{p['task_id']:04d}",
                template="mbpp",
                step_index=0,
                operator=m.operator,
                error_type=r.kind,
                system_prompt=SYSTEM_PROMPT,
                goal=goal,
                prefix_actions=[],
                prefix_observations=[],
                failed_action=m.code,
                gold_action=p["code"].strip(),
                obs_fail=obs_fail,
                obs_fail_terse=render_observation(r, len(tests), "terse", False, m.code),
                obs_fail_verbose=render_observation(
                    r, len(tests), "verbose", False, m.code
                ),
                obs_fail_echo=render_observation(
                    r, len(tests), "standard", True, m.code
                ),
                obs_success=success_observation(len(tests)),
                obs_neutral=neutral_observation(len(tests)),
                obs_fail_other=obs_other,
                distractors=distractors,
                tool=None,
                meta={
                    "traceback_quotes_source": bool(quotes),
                    "tests_passed_before_failure": r.passed,
                    "n_tests": len(tests),
                },
            )
            by_operator.setdefault(m.operator, []).append(item)

    items: List[ProbeItem] = []
    for operator in sorted(by_operator):
        items.extend(by_operator[operator][:max_per_operator])
    items.sort(key=lambda it: it.item_id)
    return items


def stratified_subsample(
    items: Sequence[ProbeItem],
    n: int,
    seed: int = 20260808,
    max_per_task: Optional[int] = None,
) -> List[ProbeItem]:
    """Deterministically thin an item set while keeping operator balance.

    CPU inference is the binding constraint in this project, so item sets are
    built large and then thinned. Thinning round-robin over operators (rather
    than taking a prefix) keeps every error family represented; capping items
    per task raises the number of independent bootstrap clusters, which is what
    the confidence intervals actually depend on.
    """
    import random as _random

    rng = _random.Random(seed)
    by_op: Dict[str, List[ProbeItem]] = {}
    for it in items:
        by_op.setdefault(it.operator, []).append(it)
    for op in by_op:
        by_op[op] = sorted(by_op[op], key=lambda i: i.item_id)
        rng.shuffle(by_op[op])

    per_task: Dict[str, int] = {}
    chosen: List[ProbeItem] = []
    ops = sorted(by_op)
    cursor = {op: 0 for op in ops}
    while len(chosen) < n and any(cursor[op] < len(by_op[op]) for op in ops):
        for op in ops:
            if len(chosen) >= n:
                break
            while cursor[op] < len(by_op[op]):
                cand = by_op[op][cursor[op]]
                cursor[op] += 1
                if max_per_task and per_task.get(cand.task_id, 0) >= max_per_task:
                    continue
                per_task[cand.task_id] = per_task.get(cand.task_id, 0) + 1
                chosen.append(cand)
                break
    chosen.sort(key=lambda i: i.item_id)
    return chosen


def save_items(items: Sequence[ProbeItem], path: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        for it in items:
            fh.write(json.dumps(asdict(it), ensure_ascii=False) + "\n")


def load_items(path: str) -> List[ProbeItem]:
    out: List[ProbeItem] = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            if line.strip():
                out.append(ProbeItem(**json.loads(line)))
    return out
