"""Emit LaTeX macros for every number that appears inline in the prose.

The manuscript never hard-codes a quantity. Counts, percentages and headline
effect sizes are written here as `\newcommand`s into `paper/tables/facts.tex`,
so a changed experiment changes the text. Anything not yet measured is emitted
as a visible placeholder rather than a plausible-looking number.
"""

from __future__ import annotations

import argparse
import ast
import glob
import json
import os
import sys
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

from slmecho.models import REGISTRY  # noqa: E402

PENDING = r"\todo{RESULT PENDING EXPERIMENT}"


def minus(s: str) -> str:
    """Swap ASCII hyphens for real minus signs in an already-formatted number.

    Only called on strings built from numbers, never on labels: `SmolLM2-135M`
    must keep its hyphen.
    """
    return s.replace("-", r"\textminus ")


def ci_str(mean: float, lo: float, hi: float, digits: int = 2) -> str:
    """`mean [lo, hi]` with signs shown, for inline use in the prose."""
    return minus(
        f"{mean:+.{digits}f}\\,\\ci{{{lo:+.{digits}f}}}{{{hi:+.{digits}f}}}"
    )


class Facts:
    def __init__(self) -> None:
        self.rows: List[str] = []
        self.missing: List[str] = []

    def add(self, name: str, value: Optional[object], fmt: str = "{}") -> None:
        macro = "\\" + name
        if value is None or (isinstance(value, float) and not np.isfinite(value)):
            self.rows.append(f"\\newcommand{{{macro}}}{{{PENDING}}}")
            self.missing.append(name)
        else:
            body = fmt.format(value)
            if isinstance(value, (int, float, np.integer, np.floating)):
                body = minus(body)
            self.rows.append(f"\\newcommand{{{macro}}}{{{body}}}")

    def write(self, path: str) -> None:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        header = (
            "% Auto-generated by scripts/make_facts.py -- do not edit.\n"
            "% Every inline number in the manuscript comes from here.\n"
        )
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(header + "\n".join(self.rows) + "\n")


def _logged_environments() -> List[dict]:
    """Every environment record the runners printed, across all run logs.

    The earliest runs predate `environment` being written into the meta files,
    but every runner has always printed the record as its first line of output,
    so the logs are the provenance of last resort.
    """
    out: List[dict] = []
    for path in sorted(glob.glob("results/logs/*.log")) + sorted(glob.glob("results/*.txt")):
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                for line in fh:
                    line = line.strip()
                    if line.startswith('{"python"'):
                        out.append(json.loads(line))
        except OSError:
            continue
    return out


def _cap_from_truncated_actions(roll_path: str) -> Optional[int]:
    """Recover the generation cap from rollouts that predate recording it.

    An action the sampler cut off mid-call is exactly `max_new_tokens` long, so
    the longest such action gives the cap. Returns None if the tokeniser is not
    available, rather than guessing.
    """
    try:
        from transformers import AutoTokenizer

        from slmecho.models import REGISTRY

        rr = pd.read_csv(roll_path)
        model_key = str(rr["model"].iloc[0])
        tok = AutoTokenizer.from_pretrained(REGISTRY[model_key].hf_id)
    except Exception:  # noqa: BLE001
        return None
    best = 0
    for _, row in rr.iterrows():
        try:
            # These round-trip through the CSV as Python list literals, and the
            # actions are full of apostrophes, so this is not JSON.
            acts = ast.literal_eval(str(row["actions"]))
            errs = ast.literal_eval(str(row["error_types"]))
        except Exception:  # noqa: BLE001
            continue
        for a, e in zip(acts, errs):
            if e == "parse_error" and a.count("(") > a.count(")"):
                best = max(best, len(tok(a, add_special_tokens=False).input_ids))
    return best or None


def _one(records: List[dict], key: str):
    vals = {r[key] for r in records if r.get(key)}
    return sorted(vals)[0] if len(vals) == 1 else (sorted(vals)[0] if vals else None)


def _num(df: pd.DataFrame, model: str, env: str, measure: str, col: str = "mean"):
    r = df[(df["model"] == model) & (df["env"] == env) & (df["measure"] == measure)]
    return float(r[col].iloc[0]) if len(r) else None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--processed", default="results/processed")
    ap.add_argument("--raw-probe", default="results/raw/probe")
    ap.add_argument("--out", default="paper/tables/facts.tex")
    args = ap.parse_args()

    f = Facts()

    # ---- dataset facts -------------------------------------------------
    summary_path = os.path.join(args.processed, "probe_summary.csv")
    items_summary = "data/items_summary.json"
    if os.path.exists(items_summary):
        js = json.load(open(items_summary, encoding="utf-8"))
        f.add("NumToolshedItemsBuilt", js["toolshed"]["n_items"])
        f.add("NumToolshedTasks", js["toolshed"]["n_tasks"])
        f.add("NumToolshedOperators", len(js["toolshed"]["operators"]))
        f.add("NumToolshedErrorTypes", len(js["toolshed"]["error_types"]))
        f.add("NumCodeItemsBuilt", js["coderepair"]["n_items"])
        f.add("NumCodeTasks", js["coderepair"]["n_tasks"])
        f.add("NumCodeOperators", len(js["coderepair"]["operators"]))
    else:
        for k in ("NumToolshedItemsBuilt", "NumToolshedTasks", "NumToolshedOperators",
                  "NumToolshedErrorTypes", "NumCodeItemsBuilt", "NumCodeTasks",
                  "NumCodeOperators"):
            f.add(k, None)

    # ---- run facts (from the per-run meta files) ------------------------
    metas = sorted(glob.glob(os.path.join(args.raw_probe, "*.meta.json")))
    saved, n_items_a, n_items_b, torch_ver, tf_ver, cpu = [], None, None, None, None, None
    for m in metas:
        js = json.load(open(m, encoding="utf-8"))
        if js.get("naive_tokens"):
            saved.append(1 - js["forward_tokens"] / js["naive_tokens"])
        if js.get("env") == "toolshed" and js.get("condition_set") == "core":
            n_items_a = js.get("n_items")
        if js.get("env") == "coderepair":
            n_items_b = js.get("n_items")
        env = js.get("environment") or {}
        torch_ver = torch_ver or env.get("torch")
        tf_ver = tf_ver or env.get("transformers")
        cpu = cpu or env.get("cpu")
    f.add("CacheSaving", np.mean(saved) * 100 if saved else None, "{:.0f}\\%")
    f.add("NumProbeItemsToolshed", n_items_a)
    f.add("NumProbeItemsCode", n_items_b)
    # No fallback literals here on purpose. A hard-coded "4.56.1" that nothing
    # measured is indistinguishable, in the finished PDF, from a version that
    # was actually recorded. Older meta files predate the environment record,
    # so fall back to the environment lines the runners printed into the logs.
    logged = _logged_environments()
    torch_ver = torch_ver or _one(logged, "torch")
    cpu = cpu or _one(logged, "cpu")
    f.add("TorchVersion", torch_ver)
    f.add("CPUName", cpu.replace("(R)", "").replace("(TM)", "") if cpu else None)
    tf_all = sorted({e["transformers"] for e in logged if e.get("transformers")})
    f.add("TransformersVersion", tf_ver or (tf_all[-1] if tf_all else None))
    # The environment was rebuilt partway through the study, so the honest
    # statement is a set, not a version.
    f.add("TransformersVersions",
          " and ".join(tf_all) if tf_all else None)
    f.add("NumTransformersVersions", len(tf_all) if tf_all else None)

    drift_path = "results/version_drift.json"
    if os.path.exists(drift_path):
        dj = json.load(open(drift_path, encoding="utf-8"))
        f.add("DriftChecked", dj.get("n_compared"))
        d = dj.get("max_abs_diff")
        # Scientific notation as maths, not as the string "4.9e-05".
        if d:
            exp = int(np.floor(np.log10(abs(d))))
            f.add("DriftMax", f"${abs(d)/10**exp:.1f}\\times 10^{{{exp}}}$")
        else:
            f.add("DriftMax", None)
        f.add("DriftModel", dj.get("model"))
    else:
        for k in ("DriftChecked", "DriftMax", "DriftModel"):
            f.add(k, None)

    # ---- model ladder ---------------------------------------------------
    if os.path.exists(summary_path):
        summary = pd.read_csv(summary_path)
        # Drop model/env cells that are still filling up: a headline average
        # should not be moved by a model with three scored items. The decision
        # is made once, in analyze_probe.py, and recorded in the CSV.
        if "published" in summary.columns:
            summary = summary[summary["published"].astype(bool)]
        else:
            summary = summary[summary["n"] >= 30]
        models = sorted(set(summary["model"]))
        fams = sorted({REGISTRY[m].family for m in models if m in REGISTRY})
        sizes = [REGISTRY[m].params_b for m in models if m in REGISTRY]
        f.add("NumModels", len(models))
        f.add("NumFamilies", len(fams))
        f.add("SmallestModel", f"{min(sizes)*1000:.0f}M" if sizes else None)
        f.add("LargestModel", f"{max(sizes):.1f}B" if sizes else None)
        f.add("FamilyList", ", ".join(fams) if fams else None)

        # ---- headline probe numbers ------------------------------------
        g = summary[(summary["measure"] == "G") & (summary["env"] == "toolshed")]
        g = g.sort_values("params_b")
        if len(g):
            neg = g[g["ci_hi"] < 0]
            f.add("NumModelsNegativeG", len(neg))
            f.add("NumModelsToolshed", len(g))
            f.add("WorstG", float(g["mean"].min()), "{:.2f}")
            f.add("WorstGModel", str(g.loc[g["mean"].idxmin(), "label"]))
            f.add("BestG", float(g["mean"].max()), "{:.2f}")
            f.add("BestGModel", str(g.loc[g["mean"].idxmax(), "label"]))
            f.add("MeanG", float(g["mean"].mean()), "{:.2f}")
            # Per-token odds multiplier. exp(-G) over a whole ~20-token action
            # is an enormous, unhelpful number; per token it is a quantity a
            # reader can hold onto.
            gt_tok = summary[(summary["measure"] == "G_per_token")
                             & (summary["env"] == "toolshed")]
            f.add("OddsPerToken",
                  float(np.exp(-gt_tok["mean"].mean())) if len(gt_tok) else None,
                  "{:.1f}")
        else:
            for k in ("NumModelsNegativeG", "NumModelsToolshed", "WorstG",
                      "WorstGModel", "BestG", "BestGModel", "MeanG",
                      "OddsPerToken"):
                f.add(k, None)

        for meas, name in (("copy", "Copy"), ("sem", "Sem"), ("polarity", "Pol"),
                           ("repair", "Repair"), ("margin_shift", "MarginShift")):
            sub = summary[(summary["measure"] == meas) & (summary["env"] == "toolshed")]
            f.add(f"Mean{name}", float(sub["mean"].mean()) if len(sub) else None, "{:.2f}")
            f.add(f"Max{name}", float(sub["mean"].max()) if len(sub) else None, "{:.2f}")
            f.add(f"Min{name}", float(sub["mean"].min()) if len(sub) else None, "{:.2f}")

        # Length control: the decomposition against a neutral observation padded
        # to the failure observation's token length.
        for meas, name in (("copy_pad", "CopyPad"), ("sem_pad", "SemPad")):
            sub = summary[(summary["measure"] == meas) & (summary["env"] == "toolshed")]
            f.add(name, float(sub["mean"].mean()) if len(sub) else None, "{:.2f}")

        # Study-2 manipulations, as paired changes against the standard harness
        # on the same items (the only fair comparison across variants that were
        # scored on different subsets). Positive = repetition made more likely.
        for meas, name in (("delta_fail_other", "DPlacebo"),
                           ("delta_fail_k2", "DTwice"),
                           ("delta_fail_k3", "DThrice"),
                           ("delta_fail_instr", "DInstruction"),
                           ("delta_fail_echo", "DEcho"),
                           ("delta_fail_terse", "DTerse"),
                           ("delta_fail_verbose", "DVerbose"),
                           ("delta_fail_early", "DEarly"),
                           ("delta_abstract", "DAbstract"),
                           ("delta_abstract_min", "DAbstractMin")):
            sub = summary[(summary["measure"] == meas) & (summary["env"] == "toolshed")]
            if len(sub):
                f.add(name, float(sub["mean"].mean()), "{:+.2f}")
                f.add(name + "CI", ci_str(float(sub["mean"].mean()),
                                          float(sub["ci_lo"].mean()),
                                          float(sub["ci_hi"].mean())))
            else:
                f.add(name, None)
                f.add(name + "CI", None)
        # `abstract_min` is only run on the deep subset, so compare it against
        # `abstract` restricted to the same models, not against a cross-model
        # mean that includes models `abstract_min` never saw.
        amin = summary[(summary["measure"] == "delta_abstract_min")
                       & (summary["env"] == "toolshed")]
        amat = summary[(summary["measure"] == "delta_abstract")
                       & (summary["env"] == "toolshed")
                       & (summary["model"].isin(set(amin["model"])))]
        f.add("DAbstractMatched",
              float(amat["mean"].mean()) if len(amat) else None, "{:+.2f}")
        if len(amat):
            f.add("DAbstractMatchedCI", ci_str(float(amat["mean"].mean()),
                                               float(amat["ci_lo"].mean()),
                                               float(amat["ci_hi"].mean())))
        else:
            f.add("DAbstractMatchedCI", None)

        plac = summary[(summary["measure"] == "delta_fail_other")
                       & (summary["env"] == "toolshed")]
        f.add("StringSpecificBound",
              abs(float(plac["mean"].mean())) if len(plac) else None, "{:.1f}")

        gcode = summary[(summary["measure"] == "G") & (summary["env"] == "coderepair")]
        f.add("MeanGCode", float(gcode["mean"].mean()) if len(gcode) else None, "{:.2f}")
        f.add("NumModelsCode", len(gcode) if len(gcode) else None)

        # Per-token gain: the quantity that is comparable across environments.
        for env_name, tag in (("toolshed", "Tool"), ("coderepair", "Code")):
            sub = summary[(summary["measure"] == "G_per_token")
                          & (summary["env"] == env_name)]
            f.add(f"GPerToken{tag}", float(sub["mean"].mean()) if len(sub) else None,
                  "{:.2f}")
            neg = summary[(summary["measure"] == "G_negative")
                          & (summary["env"] == env_name)]
            f.add(f"FracNeg{tag}", float(neg["mean"].min()) * 100 if len(neg) else None,
                  r"{:.0f}\%")
        gabs = summary[(summary["measure"] == "G_abstract")
                       & (summary["env"] == "toolshed")]
        f.add("MeanGAbstract", float(gabs["mean"].mean()) if len(gabs) else None,
              "{:.2f}")
        # How much of the inversion the abstraction removes, as a percentage.
        gt = summary[(summary["measure"] == "G") & (summary["env"] == "toolshed")]
        if len(gabs) and len(gt):
            f.add("AbstractRemoved",
                  (1 - abs(float(gabs["mean"].mean())) / abs(float(gt["mean"].mean()))) * 100,
                  r"{:.0f}\%")
        else:
            f.add("AbstractRemoved", None)
        # How lopsided the decomposition gets: the surface-form term against
        # the semantic one, at the model/environment where the gap is widest.
        cw = summary[summary["measure"] == "copy"].set_index(["model", "env"])["mean"]
        sw = summary[summary["measure"] == "sem"].set_index(["model", "env"])["mean"]
        ratio = (cw / sw.abs()).replace([np.inf, -np.inf], np.nan).dropna()
        if len(ratio):
            f.add("MaxCopySemRatio", float(ratio.max()), "{:.0f}")
            f.add("MedianCopySemRatio", float(ratio.median()), "{:.0f}")
            for env_name, tag in (("toolshed", "Tool"), ("coderepair", "Code")):
                sub = ratio[[e == env_name for _m, e in ratio.index]]
                f.add(f"CopySemRatio{tag}",
                      float(sub.median()) if len(sub) else None, "{:.0f}")
        else:
            f.add("MaxCopySemRatio", None)
            f.add("MedianCopySemRatio", None)
            f.add("CopySemRatioTool", None)
            f.add("CopySemRatioCode", None)

        copy_t = summary[(summary["measure"] == "copy") & (summary["env"] == "toolshed")]
        if len(copy_t) and len(gt):
            f.add("CopyShare",
                  float(copy_t["mean"].mean()) / abs(float(gt["mean"].mean())) * 100,
                  r"{:.0f}\%")
        else:
            f.add("CopyShare", None)

        for meas, name in (("p_repeat_pre", "PRepeatPre"),
                           ("p_repeat_fail", "PRepeatPost")):
            sub = summary[(summary["measure"] == meas) & (summary["env"] == "toolshed")]
            f.add(f"{name}Mean", float(sub["mean"].mean()) if len(sub) else None,
                  "{:.2f}")
            subc = summary[(summary["measure"] == meas)
                           & (summary["env"] == "coderepair")]
            f.add(f"{name}Code", float(subc["mean"].mean()) if len(subc) else None,
                  "{:.2f}")

        for meas, name in (("greedy_repeat_pre", "GreedyPre"),
                           ("greedy_repeat_fail", "GreedyPost"),
                           ("greedy_repeat_abstract", "GreedyAbstract")):
            sub = summary[(summary["measure"] == meas) & (summary["env"] == "toolshed")]
            f.add(f"{name}Mean", float(sub["mean"].mean()) * 100 if len(sub) else None,
                  "{:.0f}\\%")
    else:
        for k in ("NumModels", "NumFamilies", "SmallestModel", "LargestModel",
                  "FamilyList", "NumModelsNegativeG", "NumModelsToolshed", "WorstG",
                  "WorstGModel", "BestG", "BestGModel", "MeanG", "MedianOddsMult",
                  "MeanCopy", "MaxCopy", "MinCopy", "MeanSem", "MaxSem", "MinSem",
                  "MeanPol", "MaxPol", "MinPol", "MeanGCode", "NumModelsCode",
                  "GPerTokenTool", "GPerTokenCode", "FracNegTool", "FracNegCode",
                  "MeanGAbstract", "AbstractRemoved", "CopyShare",
                  "GreedyPreMean", "GreedyPostMean", "GreedyAbstractMean"):
            f.add(k, None)

    # ---- scaling fit ----------------------------------------------------
    fits_path = os.path.join(args.processed, "probe_scaling_fits.csv")
    if os.path.exists(fits_path):
        fits = pd.read_csv(fits_path)
        row = fits[(fits["env"] == "toolshed") & (fits["family"] == "all")]
        f.add("ScalingSlope", float(row["slope_per_decade"].iloc[0]) if len(row) else None, "{:.2f}")
        f.add("ScalingRsq", float(row["r2"].iloc[0]) if len(row) else None, "{:.2f}")
        cross = float(row["zero_crossing_params_b"].iloc[0]) if len(row) else None
        f.add("ZeroCrossing", cross, "{:.1f}B")
        # Leave-one-model-out spread of that same extrapolation.
        loo = fits[(fits["env"] == "toolshed")
                   & (fits["family"].astype(str).str.startswith("loo:"))]
        if len(loo):
            lo, hi = float(loo["zero_crossing_params_b"].min()), float(
                loo["zero_crossing_params_b"].max())
            f.add("ZeroCrossingLoMin", lo, "{:.0f}B")
            f.add("ZeroCrossingLoMax", hi, "{:.0f}B")
            f.add("ZeroCrossingLoRatio", hi / lo if lo else None, "{:.1f}")
        else:
            for k in ("ZeroCrossingLoMin", "ZeroCrossingLoMax",
                      "ZeroCrossingLoRatio"):
                f.add(k, None)
    else:
        f.add("ScalingSlope", None)
        f.add("ScalingRsq", None)
        f.add("ZeroCrossing", None)

    # ---- agent study ----------------------------------------------------
    #
    # Emitted per harness so the prose can name any of them without a second
    # place for a number to be wrong. `Delta*` are paired contrasts against the
    # standard harness on matched tasks, formatted with their interval.
    HARNESS_TAG = {
        "verbatim": "Verbatim", "verbatim+instr": "Instr", "drop": "Drop",
        "abstract": "Abstract", "verbatim+ban": "VerbBan", "abstract+ban": "AbsBan",
    }
    LEVEL_METRICS = (
        ("solved", "Success", 100, "{:.0f}\\%"),
        ("stuck", "Stuck", 100, "{:.0f}\\%"),
        ("exact_repeat_rate", "Repeat", 100, "{:.0f}\\%"),
        ("canonical_repeat_rate", "CanonRepeat", 100, "{:.0f}\\%"),
        ("gen_tokens", "Tokens", 1, "{:.0f}"),
    )
    agent_path = os.path.join(args.processed, "agent_summary.csv")
    a = pd.read_csv(agent_path) if os.path.exists(agent_path) else pd.DataFrame()
    for h, tag in HARNESS_TAG.items():
        for metric, mtag, scale, fmt in LEVEL_METRICS:
            sub = (a[(a["harness"] == h) & (a["metric"] == metric)]
                   if len(a) else pd.DataFrame())
            f.add(f"Agent{tag}{mtag}",
                  float(sub["mean"].mean()) * scale if len(sub) else None, fmt)
    f.add("AgentNumHarnesses", int(a["harness"].nunique()) if len(a) else None)
    f.add("AgentNumModels", int(a["model"].nunique()) if len(a) else None)
    f.add("AgentNumTasks", int(a["n"].max()) if len(a) and "n" in a else None)
    roll_path = os.path.join(args.processed, "agent_rollouts.csv")
    if os.path.exists(roll_path):
        rr = pd.read_csv(roll_path)
        f.add("AgentMaxSteps", int(rr["max_steps"].max()) if len(rr) else None)
        f.add("AgentTemperature", f"{float(rr['temperature'].max()):g}"
              if len(rr) else None)
        # The released rollouts predate this being recorded per rollout. Where
        # it is absent, recover it from the data: an action cut off by the cap
        # is exactly that many tokens long, so the longest truncated action is
        # the cap.
        if "max_new_tokens" in rr.columns and rr["max_new_tokens"].notna().any():
            f.add("AgentTokenCap", int(rr["max_new_tokens"].max()))
        else:
            f.add("AgentTokenCap", _cap_from_truncated_actions(roll_path))
    else:
        f.add("AgentMaxSteps", None)
        f.add("AgentTemperature", None)
        f.add("AgentTokenCap", None)

    base = a[(a["harness"] == "verbatim") & (a["metric"] == "solved")] if len(a) else []
    best = a[(a["harness"] == "abstract+ban") & (a["metric"] == "solved")] if len(a) else []
    f.add("AgentBaseSuccess",
          float(base["mean"].mean()) * 100 if len(base) else None, "{:.0f}\\%")
    f.add("AgentBestSuccess",
          float(best["mean"].mean()) * 100 if len(best) else None, "{:.0f}\\%")
    f.add("AgentGain",
          (float(best["mean"].mean()) - float(base["mean"].mean())) * 100
          if len(best) and len(base) else None, "{:+.0f}")
    for metric, name in (("truncated_rate", "TruncShare"),
                         ("prose_rate", "ProseShare")):
        sub = a[a["metric"] == metric] if len(a) else []
        f.add(name, float(sub["mean"].mean()) * 100 if len(sub) else None, r"{:.0f}\%")
    rb = (a[(a["harness"] == "verbatim") & (a["metric"] == "exact_repeat_rate")]
          if len(a) else [])
    f.add("AgentBaseRepeat",
          float(rb["mean"].mean()) * 100 if len(rb) else None, "{:.0f}\\%")
    rd = (a[(a["harness"] == "drop") & (a["metric"] == "exact_repeat_rate")]
          if len(a) else [])
    f.add("DropRepeatRatio",
          (float(rd["mean"].mean()) / float(rb["mean"].mean()))
          if len(rd) and len(rb) and float(rb["mean"].mean()) else None,
          "{:.1f}")

    contrast_path = os.path.join(args.processed, "agent_contrasts.csv")
    c = pd.read_csv(contrast_path) if os.path.exists(contrast_path) else pd.DataFrame()
    for h, tag in HARNESS_TAG.items():
        if h == "verbatim":
            continue
        for metric, mtag in (("solved", "Success"),
                             ("exact_repeat_rate", "Repeat"),
                             ("stuck", "Stuck")):
            sub = (c[(c["harness"] == h) & (c["metric"] == metric)]
                   if len(c) else pd.DataFrame())
            if len(sub):
                m, lo, hi = (float(sub["mean"].mean()) * 100,
                             float(sub["ci_lo"].mean()) * 100,
                             float(sub["ci_hi"].mean()) * 100)
                f.add(f"Delta{tag}{mtag}", ci_str(m, lo, hi, digits=0))
            else:
                f.add(f"Delta{tag}{mtag}", None)

    f.write(args.out)
    print(f"wrote {args.out} ({len(f.rows)} macros)")
    if f.missing:
        print(f"pending ({len(f.missing)}): {', '.join(f.missing)}")


if __name__ == "__main__":
    main()
